"""Seed the database with sample supplement data."""
from backend.database import SessionLocal, engine, Base
from backend.models import Supplement

Base.metadata.create_all(bind=engine)


SAMPLE_SUPPLEMENTS = [
    {
        "name": "Vitamin D3 5000 IU",
        "brand": "Nature's Way",
        "category": "vitamin",
        "ingredients": ["vitamin_d3", "cholecalciferol"],
        "dosage": "5000 IU daily",
        "form": "capsule",
        "serving_size": "1 capsule",
        "servings_per_container": 120,
        "price": 14.99,
        "currency": "EUR",
        "shop_name": "VitaminExpress",
        "shop_url": "https://example.com/vit-d3",
        "certifications": ["gmp"],
        "allergens": [],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Hochdosiertes Vitamin D3 zur Unterstützung des Immunsystems und der Knochengesundheit.",
        "description_en": "High-dose Vitamin D3 supporting immune system and bone health.",
    },
    {
        "name": "Omega-3 Fish Oil",
        "brand": "Nordic Naturals",
        "category": "omega",
        "ingredients": ["omega3", "epa", "dha", "fish_oil"],
        "dosage": "2 softgels daily",
        "form": "capsule",
        "serving_size": "2 softgels",
        "servings_per_container": 60,
        "price": 29.95,
        "currency": "EUR",
        "shop_name": "iHerb",
        "shop_url": "https://example.com/omega3",
        "certifications": ["ifos", "nsf"],
        "allergens": ["fish"],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Reines Omega-3 Fischöl mit hohem EPA/DHA-Gehalt für Herz und Gehirn.",
        "description_en": "Pure Omega-3 fish oil with high EPA/DHA content for heart and brain health.",
    },
    {
        "name": "Magnesium Glycinat 400mg",
        "brand": "Doctor's Best",
        "category": "mineral",
        "ingredients": ["magnesium", "magnesium_glycinate"],
        "dosage": "2 tablets daily",
        "form": "tablet",
        "serving_size": "2 tablets",
        "servings_per_container": 120,
        "price": 19.90,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://example.com/mag",
        "certifications": ["gmp", "nsf"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Gut bioverfügbares Magnesiumglycinat für Muskeln, Schlaf und Nervensystem.",
        "description_en": "Highly bioavailable magnesium glycinate for muscles, sleep and nervous system.",
    },
    {
        "name": "Vitamin B12 Methylcobalamin",
        "brand": "Jarrow Formulas",
        "category": "vitamin",
        "ingredients": ["vitamin_b12", "methylcobalamin"],
        "dosage": "1 lozenge daily",
        "form": "tablet",
        "serving_size": "1 lozenge",
        "servings_per_container": 60,
        "price": 12.50,
        "currency": "EUR",
        "shop_name": "VitaminExpress",
        "shop_url": "https://example.com/b12",
        "certifications": ["gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Methylcobalamin B12 – die aktive Form für vegane Ernährung und Energiestoffwechsel.",
        "description_en": "Methylcobalamin B12 – the active form for vegan diets and energy metabolism.",
    },
    {
        "name": "Ashwagandha KSM-66",
        "brand": "NOW Foods",
        "category": "herbal",
        "ingredients": ["ashwagandha", "ksm66", "withanolides"],
        "dosage": "1 capsule twice daily",
        "form": "capsule",
        "serving_size": "1 capsule",
        "servings_per_container": 90,
        "price": 22.00,
        "currency": "EUR",
        "shop_name": "iHerb",
        "shop_url": "https://example.com/ashwa",
        "certifications": ["gmp", "organic"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "moderate",
        "description_de": "KSM-66 Ashwagandha für Stressreduktion, besseren Schlaf und mentale Klarheit.",
        "description_en": "KSM-66 Ashwagandha for stress reduction, better sleep and mental clarity.",
    },
    {
        "name": "Probiotik 50 Milliarden",
        "brand": "Garden of Life",
        "category": "probiotic",
        "ingredients": ["probiotics", "lactobacillus", "bifidobacterium"],
        "dosage": "1 capsule daily",
        "form": "capsule",
        "serving_size": "1 capsule",
        "servings_per_container": 30,
        "price": 34.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://example.com/probio",
        "certifications": ["organic", "nsf"],
        "allergens": ["dairy"],
        "is_vegan": False,
        "is_organic": True,
        "evidence_level": "moderate",
        "description_de": "50 Milliarden KBE Probiotika für eine gesunde Darmflora und Verdauung.",
        "description_en": "50 billion CFU probiotics for healthy gut flora and digestion.",
    },
    {
        "name": "Zink 25mg Bisglycinat",
        "brand": "Natural Elements",
        "category": "mineral",
        "ingredients": ["zinc", "zinc_bisglycinate"],
        "dosage": "1 tablet daily",
        "form": "tablet",
        "serving_size": "1 tablet",
        "servings_per_container": 365,
        "price": 16.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://example.com/zinc",
        "certifications": ["gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Hoch bioverfügbares Zinkbisglycinat für Immunsystem, Haut und Haare.",
        "description_en": "Highly bioavailable zinc bisglycinate for immune system, skin and hair.",
    },
    {
        "name": "Kreatin Monohydrat",
        "brand": "Optimum Nutrition",
        "category": "amino_acid",
        "ingredients": ["creatine", "creatine_monohydrate"],
        "dosage": "5g daily",
        "form": "powder",
        "serving_size": "1 scoop (5g)",
        "servings_per_container": 60,
        "price": 24.99,
        "currency": "EUR",
        "shop_name": "MyProtein",
        "shop_url": "https://example.com/creatine",
        "certifications": ["informed_sport"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Reines Kreatin Monohydrat für Muskelaufbau, Kraft und kognitive Leistung.",
        "description_en": "Pure creatine monohydrate for muscle building, strength and cognitive performance.",
    },
    {
        "name": "Vitamin C 1000mg + Bioflavonoide",
        "brand": "Solgar",
        "category": "vitamin",
        "ingredients": ["vitamin_c", "ascorbic_acid", "bioflavonoids", "rose_hips"],
        "dosage": "1 tablet daily",
        "form": "tablet",
        "serving_size": "1 tablet",
        "servings_per_container": 100,
        "price": 18.50,
        "currency": "EUR",
        "shop_name": "VitaminExpress",
        "shop_url": "https://example.com/vitc",
        "certifications": ["gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Hochdosiertes Vitamin C mit Bioflavonoiden für das Immunsystem und Antioxidation.",
        "description_en": "High-dose Vitamin C with bioflavonoids for immune support and antioxidant protection.",
    },
    {
        "name": "Algen Omega-3 DHA+EPA",
        "brand": "Testa",
        "category": "omega",
        "ingredients": ["omega3", "dha", "epa", "algae_oil"],
        "dosage": "1 capsule daily",
        "form": "capsule",
        "serving_size": "1 capsule",
        "servings_per_container": 60,
        "price": 27.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://example.com/algae-omega",
        "certifications": ["vegan_society", "gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Veganes Omega-3 aus Algenöl – nachhaltige Alternative zu Fischöl.",
        "description_en": "Vegan Omega-3 from algae oil – sustainable alternative to fish oil.",
    },
    {
        "name": "Eisen + Vitamin C",
        "brand": "Floradix",
        "category": "mineral",
        "ingredients": ["iron", "vitamin_c", "b_vitamins", "herbal_extracts"],
        "dosage": "20ml daily",
        "form": "liquid",
        "serving_size": "20ml",
        "servings_per_container": 25,
        "price": 21.90,
        "currency": "EUR",
        "shop_name": "DM",
        "shop_url": "https://example.com/floradix",
        "certifications": ["organic"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "moderate",
        "description_de": "Flüssiges Eisen mit Vitamin C und Kräuterextrakten für bessere Aufnahme.",
        "description_en": "Liquid iron with Vitamin C and herbal extracts for better absorption.",
    },
    {
        "name": "Kollagen Peptide",
        "brand": "Vital Proteins",
        "category": "amino_acid",
        "ingredients": ["collagen", "collagen_peptides", "hyaluronic_acid"],
        "dosage": "2 scoops daily",
        "form": "powder",
        "serving_size": "2 scoops (20g)",
        "servings_per_container": 14,
        "price": 32.99,
        "currency": "EUR",
        "shop_name": "Douglas",
        "shop_url": "https://example.com/collagen",
        "certifications": ["nsf"],
        "allergens": [],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "moderate",
        "description_de": "Kollagen Peptide für Haut, Haare, Nägel und Gelenke.",
        "description_en": "Collagen peptides for skin, hair, nails and joints.",
    },
]


def seed_database():
    db = SessionLocal()
    try:
        existing_count = db.query(Supplement).count()
        if existing_count > 0:
            print(f"Database already has {existing_count} supplements. Skipping seed.")
            return

        for data in SAMPLE_SUPPLEMENTS:
            supplement = Supplement(**data)
            db.add(supplement)

        db.commit()
        print(f"Seeded {len(SAMPLE_SUPPLEMENTS)} supplements into database.")
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
