"""Seed the database with sample supplement data."""
from backend.database import SessionLocal, engine, Base, ensure_database_schema
from backend.models import Supplement

Base.metadata.create_all(bind=engine)
ensure_database_schema()


SAMPLE_SUPPLEMENTS = [
    {
        "name": "Vitamin D3 5000 IU",
        "brand": "Nature's Way",
        "category": "vitamin",
        "ingredients": ["vitamin_d3", "cholecalciferol"],
        "dosage": "5000 IU daily",
        "form": "capsule",
        "serving_size": "1 capsule",
        "servings_per_container": 120,
        "price": 14.99,
        "currency": "EUR",
        "shop_name": "VitaminExpress",
        "shop_url": "https://example.com/vit-d3",
        "certifications": ["gmp"],
        "allergens": [],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Hochdosiertes Vitamin D3 zur Unterstützung des Immunsystems und der Knochengesundheit.",
        "description_en": "High-dose Vitamin D3 supporting immune system and bone health.",
    },
    {
        "name": "Omega-3 Fish Oil",
        "brand": "Nordic Naturals",
        "category": "omega",
        "ingredients": ["omega3", "epa", "dha", "fish_oil"],
        "dosage": "2 softgels daily",
        "form": "capsule",
        "serving_size": "2 softgels",
        "servings_per_container": 60,
        "price": 29.95,
        "currency": "EUR",
        "shop_name": "iHerb",
        "shop_url": "https://example.com/omega3",
        "certifications": ["ifos", "nsf"],
        "allergens": ["fish"],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Reines Omega-3 Fischöl mit hohem EPA/DHA-Gehalt für Herz und Gehirn.",
        "description_en": "Pure Omega-3 fish oil with high EPA/DHA content for heart and brain health.",
    },
    {
        "name": "Magnesium Glycinat 400mg",
        "brand": "Doctor's Best",
        "category": "mineral",
        "ingredients": ["magnesium", "magnesium_glycinate"],
        "dosage": "2 tablets daily",
        "form": "tablet",
        "serving_size": "2 tablets",
        "servings_per_container": 120,
        "price": 19.90,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://example.com/mag",
        "certifications": ["gmp", "nsf"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Gut bioverfügbares Magnesiumglycinat für Muskeln, Schlaf und Nervensystem.",
        "description_en": "Highly bioavailable magnesium glycinate for muscles, sleep and nervous system.",
    },
    {
        "name": "Vitamin B12 Methylcobalamin",
        "brand": "Jarrow Formulas",
        "category": "vitamin",
        "ingredients": ["vitamin_b12", "methylcobalamin"],
        "dosage": "1 lozenge daily",
        "form": "tablet",
        "serving_size": "1 lozenge",
        "servings_per_container": 60,
        "price": 12.50,
        "currency": "EUR",
        "shop_name": "VitaminExpress",
        "shop_url": "https://example.com/b12",
        "certifications": ["gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Methylcobalamin B12 – die aktive Form für vegane Ernährung und Energiestoffwechsel.",
        "description_en": "Methylcobalamin B12 – the active form for vegan diets and energy metabolism.",
    },
    {
        "name": "Ashwagandha KSM-66",
        "brand": "NOW Foods",
        "category": "herbal",
        "ingredients": ["ashwagandha", "ksm66", "withanolides"],
        "dosage": "1 capsule twice daily",
        "form": "capsule",
        "serving_size": "1 capsule",
        "servings_per_container": 90,
        "price": 22.00,
        "currency": "EUR",
        "shop_name": "iHerb",
        "shop_url": "https://example.com/ashwa",
        "certifications": ["gmp", "organic"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "moderate",
        "description_de": "KSM-66 Ashwagandha für Stressreduktion, besseren Schlaf und mentale Klarheit.",
        "description_en": "KSM-66 Ashwagandha for stress reduction, better sleep and mental clarity.",
    },
    {
        "name": "Probiotik 50 Milliarden",
        "brand": "Garden of Life",
        "category": "probiotic",
        "ingredients": ["probiotics", "lactobacillus", "bifidobacterium"],
        "dosage": "1 capsule daily",
        "form": "capsule",
        "serving_size": "1 capsule",
        "servings_per_container": 30,
        "price": 34.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://example.com/probio",
        "certifications": ["organic", "nsf"],
        "allergens": ["dairy"],
        "is_vegan": False,
        "is_organic": True,
        "evidence_level": "moderate",
        "description_de": "50 Milliarden KBE Probiotika für eine gesunde Darmflora und Verdauung.",
        "description_en": "50 billion CFU probiotics for healthy gut flora and digestion.",
    },
    {
        "name": "Zink 25mg Bisglycinat",
        "brand": "Natural Elements",
        "category": "mineral",
        "ingredients": ["zinc", "zinc_bisglycinate"],
        "dosage": "1 tablet daily",
        "form": "tablet",
        "serving_size": "1 tablet",
        "servings_per_container": 365,
        "price": 16.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://example.com/zinc",
        "certifications": ["gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Hoch bioverfügbares Zinkbisglycinat für Immunsystem, Haut und Haare.",
        "description_en": "Highly bioavailable zinc bisglycinate for immune system, skin and hair.",
    },
    {
        "name": "Kreatin Monohydrat",
        "brand": "Optimum Nutrition",
        "category": "amino_acid",
        "ingredients": ["creatine", "creatine_monohydrate"],
        "dosage": "5g daily",
        "form": "powder",
        "serving_size": "1 scoop (5g)",
        "servings_per_container": 60,
        "price": 24.99,
        "currency": "EUR",
        "shop_name": "MyProtein",
        "shop_url": "https://example.com/creatine",
        "certifications": ["informed_sport"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Reines Kreatin Monohydrat für Muskelaufbau, Kraft und kognitive Leistung.",
        "description_en": "Pure creatine monohydrate for muscle building, strength and cognitive performance.",
    },
    {
        "name": "Vitamin C 1000mg + Bioflavonoide",
        "brand": "Solgar",
        "category": "vitamin",
        "ingredients": ["vitamin_c", "ascorbic_acid", "bioflavonoids", "rose_hips"],
        "dosage": "1 tablet daily",
        "form": "tablet",
        "serving_size": "1 tablet",
        "servings_per_container": 100,
        "price": 18.50,
        "currency": "EUR",
        "shop_name": "VitaminExpress",
        "shop_url": "https://example.com/vitc",
        "certifications": ["gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Hochdosiertes Vitamin C mit Bioflavonoiden für das Immunsystem und Antioxidation.",
        "description_en": "High-dose Vitamin C with bioflavonoids for immune support and antioxidant protection.",
    },
    {
        "name": "Algen Omega-3 DHA+EPA",
        "brand": "Testa",
        "category": "omega",
        "ingredients": ["omega3", "dha", "epa", "algae_oil"],
        "dosage": "1 capsule daily",
        "form": "capsule",
        "serving_size": "1 capsule",
        "servings_per_container": 60,
        "price": 27.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://example.com/algae-omega",
        "certifications": ["vegan_society", "gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Veganes Omega-3 aus Algenöl – nachhaltige Alternative zu Fischöl.",
        "description_en": "Vegan Omega-3 from algae oil – sustainable alternative to fish oil.",
    },
    {
        "name": "Eisen + Vitamin C",
        "brand": "Floradix",
        "category": "mineral",
        "ingredients": ["iron", "vitamin_c", "b_vitamins", "herbal_extracts"],
        "dosage": "20ml daily",
        "form": "liquid",
        "serving_size": "20ml",
        "servings_per_container": 25,
        "price": 21.90,
        "currency": "EUR",
        "shop_name": "DM",
        "shop_url": "https://example.com/floradix",
        "certifications": ["organic"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "moderate",
        "description_de": "Flüssiges Eisen mit Vitamin C und Kräuterextrakten für bessere Aufnahme.",
        "description_en": "Liquid iron with Vitamin C and herbal extracts for better absorption.",
    },
    {
        "name": "Kollagen Peptide",
        "brand": "Vital Proteins",
        "category": "amino_acid",
        "ingredients": ["collagen", "collagen_peptides", "hyaluronic_acid"],
        "dosage": "2 scoops daily",
        "form": "powder",
        "serving_size": "2 scoops (20g)",
        "servings_per_container": 14,
        "price": 32.99,
        "currency": "EUR",
        "shop_name": "Douglas",
        "shop_url": "https://example.com/collagen",
        "certifications": ["nsf"],
        "allergens": [],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "moderate",
        "description_de": "Kollagen Peptide für Haut, Haare, Nägel und Gelenke.",
        "description_en": "Collagen peptides for skin, hair, nails and joints.",
    },
    # === ADDITIONAL PRODUCTS ===
    {
        "name": "Vitamin D3 + K2 Tropfen",
        "brand": "Nature Love",
        "category": "vitamin",
        "ingredients": ["vitamin_d3", "vitamin_k2", "mct_oil"],
        "dosage": "1 Tropfen täglich",
        "form": "liquid",
        "serving_size": "1 Tropfen",
        "servings_per_container": 1700,
        "price": 24.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://www.amazon.de/dp/B01N7GD2Z7",
        "certifications": ["gmp", "vegan"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Hochdosiertes Vitamin D3 + K2 in Tropfenform für optimale Aufnahme. 1700 Tropfen pro Flasche.",
        "description_en": "High-dose Vitamin D3 + K2 drops for optimal absorption. 1700 drops per bottle.",
    },
    {
        "name": "Bio Kurkuma Kapseln",
        "brand": "Biotiva",
        "category": "herbal",
        "ingredients": ["turmeric", "curcumin", "black_pepper", "piperine"],
        "dosage": "2 Kapseln täglich",
        "form": "capsule",
        "serving_size": "2 Kapseln",
        "servings_per_container": 90,
        "price": 16.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://www.amazon.de/dp/B01HPBJF8G",
        "certifications": ["organic", "gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "moderate",
        "description_de": "Bio-Kurkuma mit Piperin für bessere Bioverfügbarkeit. Entzündungshemmend und antioxidativ.",
        "description_en": "Organic turmeric with piperine for better bioavailability. Anti-inflammatory and antioxidant.",
    },
    {
        "name": "Multivitamin A-Z Komplex",
        "brand": "Doppelherz",
        "category": "vitamin",
        "ingredients": ["vitamin_a", "vitamin_c", "vitamin_d", "vitamin_e", "b_vitamins", "zinc", "iron", "magnesium"],
        "dosage": "1 Tablette täglich",
        "form": "tablet",
        "serving_size": "1 Tablette",
        "servings_per_container": 100,
        "price": 9.99,
        "currency": "EUR",
        "shop_name": "Rossmann",
        "shop_url": "https://www.rossmann.de/de/gesundheit-doppelherz-a-z-komplett/p/4009932131789",
        "certifications": [],
        "allergens": [],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "moderate",
        "description_de": "Umfassender Multivitamin-Komplex mit allen wichtigen Vitaminen und Mineralstoffen für den Alltag.",
        "description_en": "Comprehensive multivitamin complex with all essential vitamins and minerals for everyday use.",
    },
    {
        "name": "Omega-3 vegan Algenöl",
        "brand": "Natural Elements",
        "category": "omega",
        "ingredients": ["omega3", "dha", "epa", "algae_oil"],
        "dosage": "1 Kapsel täglich",
        "form": "capsule",
        "serving_size": "1 Kapsel",
        "servings_per_container": 90,
        "price": 24.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://www.amazon.de/dp/B07QMF5NZJ",
        "certifications": ["gmp", "vegan_society"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Veganes Omega-3 aus nachhaltigem Algenöl. Hoher DHA- und EPA-Gehalt ohne Fisch.",
        "description_en": "Vegan Omega-3 from sustainable algae oil. High DHA and EPA content without fish.",
    },
    {
        "name": "Bio Ashwagandha Pulver",
        "brand": "Biotiva",
        "category": "herbal",
        "ingredients": ["ashwagandha", "withanolides"],
        "dosage": "1 TL täglich",
        "form": "powder",
        "serving_size": "3g",
        "servings_per_container": 66,
        "price": 13.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://www.amazon.de/dp/B01N5F7LVS",
        "certifications": ["organic"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "moderate",
        "description_de": "Reines Bio-Ashwagandha-Pulver zum Einrühren. Unterstützt Stressabbau und innere Ruhe.",
        "description_en": "Pure organic ashwagandha powder for mixing. Supports stress relief and inner calm.",
    },
    {
        "name": "Magnesium 400 Brausetabletten",
        "brand": "Abtei",
        "category": "mineral",
        "ingredients": ["magnesium", "magnesium_citrate"],
        "dosage": "1 Brausetablette täglich",
        "form": "tablet",
        "serving_size": "1 Brausetablette",
        "servings_per_container": 30,
        "price": 5.49,
        "currency": "EUR",
        "shop_name": "DM",
        "shop_url": "https://www.dm.de/abtei-magnesium-400-brausetabletten-p4026600173063.html",
        "certifications": [],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Magnesium-Brausetabletten mit Zitronengeschmack. Günstig und effektiv für Muskeln und Nerven.",
        "description_en": "Magnesium effervescent tablets with lemon flavor. Affordable and effective for muscles and nerves.",
    },
    {
        "name": "Protein Pulver Whey Isolat",
        "brand": "ESN",
        "category": "amino_acid",
        "ingredients": ["protein", "whey_isolate", "bcaa"],
        "dosage": "30g nach dem Training",
        "form": "powder",
        "serving_size": "30g",
        "servings_per_container": 30,
        "price": 32.90,
        "currency": "EUR",
        "shop_name": "Fitmart",
        "shop_url": "https://www.fitmart.de/esn-designer-whey-protein",
        "certifications": ["informed_sport"],
        "allergens": ["lactose"],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Hochwertiges Whey-Isolat für schnelle Muskelregeneration. 25g Protein pro Portion.",
        "description_en": "Premium whey isolate for fast muscle recovery. 25g protein per serving.",
    },
    {
        "name": "Vegan Protein Bio",
        "brand": "Sunwarrior",
        "category": "amino_acid",
        "ingredients": ["protein", "pea_protein", "rice_protein", "hemp_protein"],
        "dosage": "25g täglich",
        "form": "powder",
        "serving_size": "25g",
        "servings_per_container": 30,
        "price": 39.99,
        "currency": "EUR",
        "shop_name": "iHerb",
        "shop_url": "https://de.iherb.com/pr/sunwarrior-warrior-blend-organic-plant-based-protein/82451",
        "certifications": ["organic", "vegan_society"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "moderate",
        "description_de": "Bio-veganes Proteinpulver aus Erbsen-, Reis- und Hanfprotein. Vollständiges Aminosäureprofil.",
        "description_en": "Organic vegan protein powder from pea, rice and hemp protein. Complete amino acid profile.",
    },
    {
        "name": "Probiotika Bio Komplex",
        "brand": "Nature Love",
        "category": "probiotic",
        "ingredients": ["probiotics", "lactobacillus", "bifidobacterium", "inulin"],
        "dosage": "1 Kapsel täglich",
        "form": "capsule",
        "serving_size": "1 Kapsel",
        "servings_per_container": 120,
        "price": 22.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://www.amazon.de/dp/B078WRY81H",
        "certifications": ["organic", "gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "moderate",
        "description_de": "Bio-Probiotika mit 20 Bakterienstämmen und Inulin. 20 Mrd. KBE pro Kapsel.",
        "description_en": "Organic probiotics with 20 bacterial strains and inulin. 20 billion CFU per capsule.",
    },
    {
        "name": "Vitamin B12 Spray",
        "brand": "BetterYou",
        "category": "vitamin",
        "ingredients": ["vitamin_b12", "methylcobalamin"],
        "dosage": "4 Sprühstöße täglich",
        "form": "liquid",
        "serving_size": "4 Sprühstöße",
        "servings_per_container": 48,
        "price": 15.99,
        "currency": "EUR",
        "shop_name": "Apotheke",
        "shop_url": "https://www.shop-apotheke.com/betteryou-b12-boost-oral-spray",
        "certifications": ["vegan"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Vitamin B12 als Mundspray für schnelle sublinguale Aufnahme. Ideal für Veganer.",
        "description_en": "Vitamin B12 oral spray for fast sublingual absorption. Ideal for vegans.",
    },
    {
        "name": "Calcium + D3 Tabletten",
        "brand": "Taxofit",
        "category": "mineral",
        "ingredients": ["calcium", "vitamin_d3"],
        "dosage": "1 Tablette täglich",
        "form": "tablet",
        "serving_size": "1 Tablette",
        "servings_per_container": 40,
        "price": 4.95,
        "currency": "EUR",
        "shop_name": "Rossmann",
        "shop_url": "https://www.rossmann.de/de/gesundheit-taxofit-calcium-d3/p/4008617037002",
        "certifications": [],
        "allergens": ["lactose"],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Calcium mit Vitamin D3 für Knochen und Zähne. Preiswert in der Drogerie erhältlich.",
        "description_en": "Calcium with Vitamin D3 for bones and teeth. Affordable, available in drugstores.",
    },
    {
        "name": "Bio Spirulina Presslinge",
        "brand": "Wörwag Pharma",
        "category": "herbal",
        "ingredients": ["spirulina", "chlorophyll", "iron", "b_vitamins"],
        "dosage": "6 Presslinge täglich",
        "form": "tablet",
        "serving_size": "6 Presslinge",
        "servings_per_container": 66,
        "price": 19.90,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://www.amazon.de/dp/B00FFZAF1M",
        "certifications": ["organic"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "moderate",
        "description_de": "Bio-Spirulina-Presslinge mit hohem Eisen- und Chlorophyllgehalt. Natürliche Nährstoffquelle.",
        "description_en": "Organic spirulina tablets with high iron and chlorophyll content. Natural nutrient source.",
    },
    {
        "name": "Glucosamin + Chondroitin",
        "brand": "Doppelherz",
        "category": "amino_acid",
        "ingredients": ["glucosamine", "chondroitin", "collagen", "vitamin_c"],
        "dosage": "1 Kapsel täglich",
        "form": "capsule",
        "serving_size": "1 Kapsel",
        "servings_per_container": 40,
        "price": 11.49,
        "currency": "EUR",
        "shop_name": "DM",
        "shop_url": "https://www.dm.de/doppelherz-glucosamin-chondroitin-p4009932131802.html",
        "certifications": [],
        "allergens": ["shellfish"],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "moderate",
        "description_de": "Glucosamin und Chondroitin für Gelenkgesundheit und Mobilität. Mit Vitamin C und Kollagen.",
        "description_en": "Glucosamine and chondroitin for joint health and mobility. With Vitamin C and collagen.",
    },
    {
        "name": "Eisentabletten vegan",
        "brand": "Natural Elements",
        "category": "mineral",
        "ingredients": ["iron", "vitamin_c", "folic_acid"],
        "dosage": "1 Tablette täglich",
        "form": "tablet",
        "serving_size": "1 Tablette",
        "servings_per_container": 240,
        "price": 14.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://www.amazon.de/dp/B07F3J7P3R",
        "certifications": ["gmp", "vegan"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Eisen + Vitamin C für optimale Aufnahme. 240 Tabletten – Vorrat für 8 Monate.",
        "description_en": "Iron + Vitamin C for optimal absorption. 240 tablets – 8 months supply.",
    },
    {
        "name": "Bio Gerstengras Pulver",
        "brand": "Jomu",
        "category": "herbal",
        "ingredients": ["barley_grass", "chlorophyll", "iron", "vitamin_c", "fiber"],
        "dosage": "2 TL täglich",
        "form": "powder",
        "serving_size": "6g",
        "servings_per_container": 50,
        "price": 29.90,
        "currency": "EUR",
        "shop_name": "Jomu Shop",
        "shop_url": "https://www.jomu.de/bio-gerstengras-pulver",
        "certifications": ["organic"],
        "allergens": ["gluten"],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "emerging",
        "description_de": "Bio-Gerstengras-Pulver aus deutschem Anbau. Reich an Chlorophyll, Eisen und Ballaststoffen.",
        "description_en": "Organic barley grass powder from German farms. Rich in chlorophyll, iron and fiber.",
    },
    {
        "name": "Melatonin Spray 0.5mg",
        "brand": "Dr. Theiss",
        "category": "herbal",
        "ingredients": ["melatonin", "l_theanine"],
        "dosage": "2 Sprühstöße vor dem Schlafengehen",
        "form": "liquid",
        "serving_size": "2 Sprühstöße",
        "servings_per_container": 60,
        "price": 8.99,
        "currency": "EUR",
        "shop_name": "DM",
        "shop_url": "https://www.dm.de/dr-theiss-melatonin-einschlaf-spray-p4016369698396.html",
        "certifications": [],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Melatonin-Spray für schnelleres Einschlafen. 0.5mg pro Dosis – rezeptfrei in DE.",
        "description_en": "Melatonin spray for faster sleep onset. 0.5mg per dose – OTC in Germany.",
    },
    {
        "name": "OPC Traubenkernextrakt",
        "brand": "Nature Love",
        "category": "herbal",
        "ingredients": ["opc", "grape_seed_extract", "vitamin_c"],
        "dosage": "1 Kapsel täglich",
        "form": "capsule",
        "serving_size": "1 Kapsel",
        "servings_per_container": 240,
        "price": 21.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://www.amazon.de/dp/B072M22QZR",
        "certifications": ["gmp", "vegan"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "moderate",
        "description_de": "OPC aus französischem Traubenkernextrakt mit Vitamin C. Starkes Antioxidans.",
        "description_en": "OPC from French grape seed extract with Vitamin C. Powerful antioxidant.",
    },
    {
        "name": "Bio Chia Samen",
        "brand": "Alnatura",
        "category": "herbal",
        "ingredients": ["omega3", "fiber", "protein", "calcium", "iron"],
        "dosage": "15g täglich",
        "form": "powder",
        "serving_size": "15g",
        "servings_per_container": 26,
        "price": 4.49,
        "currency": "EUR",
        "shop_name": "DM",
        "shop_url": "https://www.dm.de/alnatura-bio-chia-samen-p4104420205444.html",
        "certifications": ["organic", "fairtrade"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "moderate",
        "description_de": "Bio- und Fairtrade-Chia-Samen. Reich an Omega-3, Ballaststoffen und Protein.",
        "description_en": "Organic and Fairtrade chia seeds. Rich in Omega-3, fiber and protein.",
    },
    {
        "name": "L-Carnitin 1000mg",
        "brand": "Ironmaxx",
        "category": "amino_acid",
        "ingredients": ["l_carnitine"],
        "dosage": "1 Kapsel täglich",
        "form": "capsule",
        "serving_size": "1 Kapsel",
        "servings_per_container": 130,
        "price": 18.90,
        "currency": "EUR",
        "shop_name": "Fitmart",
        "shop_url": "https://www.fitmart.de/ironmaxx-l-carnitin",
        "certifications": [],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "moderate",
        "description_de": "L-Carnitin für Fettverbrennung und Energiestoffwechsel. 1000mg pro Kapsel.",
        "description_en": "L-Carnitine for fat burning and energy metabolism. 1000mg per capsule.",
    },
    {
        "name": "Rhodiola Rosea Extrakt",
        "brand": "Sunday Natural",
        "category": "herbal",
        "ingredients": ["rhodiola", "rosavins", "salidroside"],
        "dosage": "1 Kapsel täglich",
        "form": "capsule",
        "serving_size": "1 Kapsel",
        "servings_per_container": 120,
        "price": 19.90,
        "currency": "EUR",
        "shop_name": "Sunday Natural",
        "shop_url": "https://www.sunday.de/rhodiola-rosea-extrakt-kapseln.html",
        "certifications": ["gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "moderate",
        "description_de": "Rhodiola Rosea (Rosenwurz) zur Steigerung der mentalen und physischen Leistung.",
        "description_en": "Rhodiola Rosea (golden root) for enhanced mental and physical performance.",
    },
    {
        "name": "Bio Ingwer Kapseln",
        "brand": "Hübner",
        "category": "herbal",
        "ingredients": ["ginger", "gingerols"],
        "dosage": "2 Kapseln täglich",
        "form": "capsule",
        "serving_size": "2 Kapseln",
        "servings_per_container": 30,
        "price": 12.95,
        "currency": "EUR",
        "shop_name": "Reformhaus",
        "shop_url": "https://www.reformhaus.de/huebner-ingwer-kapseln",
        "certifications": ["organic"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "moderate",
        "description_de": "Bio-Ingwer-Kapseln gegen Übelkeit und für die Verdauung. Traditionelle Heilpflanze.",
        "description_en": "Organic ginger capsules for nausea and digestion. Traditional medicinal plant.",
    },
    {
        "name": "Vitamin C Lutschtabletten",
        "brand": "Vitasprint",
        "category": "vitamin",
        "ingredients": ["vitamin_c", "ascorbic_acid", "zinc"],
        "dosage": "1 Tablette täglich",
        "form": "gummy",
        "serving_size": "1 Lutschtablette",
        "servings_per_container": 60,
        "price": 7.99,
        "currency": "EUR",
        "shop_name": "Rossmann",
        "shop_url": "https://www.rossmann.de/de/gesundheit-vitasprint-vitamin-c-lutschtabletten/p/4009932007831",
        "certifications": [],
        "allergens": [],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Vitamin C Lutschtabletten mit Zink. Leckerer Orangengeschmack für das Immunsystem.",
        "description_en": "Vitamin C lozenges with zinc. Delicious orange taste for immune support.",
    },
    {
        "name": "Elektrolyte Pulver",
        "brand": "Myprotein",
        "category": "mineral",
        "ingredients": ["electrolytes", "sodium", "potassium", "magnesium", "calcium"],
        "dosage": "1 Messlöffel in 500ml Wasser",
        "form": "powder",
        "serving_size": "5g",
        "servings_per_container": 50,
        "price": 14.99,
        "currency": "EUR",
        "shop_name": "Myprotein",
        "shop_url": "https://www.myprotein.de/sporternaehrung/elektrolyt-pulver/11084988.html",
        "certifications": ["informed_sport"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Elektrolyt-Pulver für Sportler. Optimal für Regeneration und Flüssigkeitshaushalt.",
        "description_en": "Electrolyte powder for athletes. Optimal for recovery and fluid balance.",
    },
    # === SAME SUPPLEMENT, DIFFERENT BRANDS/SHOPS ===
    # --- Magnesium Vergleich (5 Varianten) ---
    {
        "name": "Magnesium Citrat 200mg",
        "brand": "Nature Love",
        "category": "mineral",
        "ingredients": ["magnesium", "magnesium_citrate"],
        "dosage": "2 Kapseln täglich",
        "form": "capsule",
        "serving_size": "2 Kapseln",
        "servings_per_container": 90,
        "price": 17.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://www.amazon.de/dp/B073R4F3FP",
        "certifications": ["gmp", "vegan"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Magnesiumcitrat in Kapseln – gut verträglich und hoch bioverfügbar.",
        "description_en": "Magnesium citrate capsules – well tolerated and highly bioavailable.",
    },
    {
        "name": "Magnesium 375mg Komplex",
        "brand": "Nu U Nutrition",
        "category": "mineral",
        "ingredients": ["magnesium", "magnesium_oxide", "magnesium_citrate"],
        "dosage": "1 Tablette täglich",
        "form": "tablet",
        "serving_size": "1 Tablette",
        "servings_per_container": 180,
        "price": 13.97,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://www.amazon.de/dp/B01B5LB45Q",
        "certifications": ["gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "moderate",
        "description_de": "Magnesium-Komplex aus Oxid und Citrat. 180 Tabletten – Vorrat für 6 Monate.",
        "description_en": "Magnesium complex from oxide and citrate. 180 tablets – 6 month supply.",
    },
    {
        "name": "Magnesium Verla N",
        "brand": "Verla",
        "category": "mineral",
        "ingredients": ["magnesium", "magnesium_citrate", "magnesium_bis_glycinate"],
        "dosage": "2 Tabletten täglich",
        "form": "tablet",
        "serving_size": "2 Tabletten",
        "servings_per_container": 100,
        "price": 18.49,
        "currency": "EUR",
        "shop_name": "Shop-Apotheke",
        "shop_url": "https://www.shop-apotheke.com/arzneimittel/magnesium-verla-n",
        "certifications": [],
        "allergens": [],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Apotheken-Magnesium von Verla. Bewährte Qualität bei Muskelkrämpfen und Verspannungen.",
        "description_en": "Pharmacy-grade magnesium by Verla. Proven quality for muscle cramps and tension.",
    },
    {
        "name": "Magnesium Pulver Pur",
        "brand": "Bulk",
        "category": "mineral",
        "ingredients": ["magnesium", "magnesium_citrate"],
        "dosage": "3g täglich in Wasser",
        "form": "powder",
        "serving_size": "3g",
        "servings_per_container": 83,
        "price": 9.99,
        "currency": "EUR",
        "shop_name": "Bulk",
        "shop_url": "https://www.bulk.com/de/magnesium-citrat-pulver.html",
        "certifications": ["gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Reines Magnesiumcitrat-Pulver ohne Zusätze. Günstigste Option pro Portion.",
        "description_en": "Pure magnesium citrate powder without additives. Most affordable option per serving.",
    },
    # --- Vitamin D3 Vergleich (4 Varianten) ---
    {
        "name": "Vitamin D3 1000 IE Tabletten",
        "brand": "Abtei",
        "category": "vitamin",
        "ingredients": ["vitamin_d3", "cholecalciferol"],
        "dosage": "1 Tablette täglich",
        "form": "tablet",
        "serving_size": "1 Tablette",
        "servings_per_container": 42,
        "price": 3.49,
        "currency": "EUR",
        "shop_name": "DM",
        "shop_url": "https://www.dm.de/abtei-vitamin-d3-1000-tabletten-p4026600153355.html",
        "certifications": [],
        "allergens": [],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Günstige Vitamin D3 Tabletten aus der Drogerie. 1000 IE pro Tablette.",
        "description_en": "Affordable Vitamin D3 tablets from drugstore. 1000 IU per tablet.",
    },
    {
        "name": "Vitamin D3 Depot 20.000 IE",
        "brand": "Natural Elements",
        "category": "vitamin",
        "ingredients": ["vitamin_d3", "cholecalciferol"],
        "dosage": "1 Tablette alle 20 Tage",
        "form": "tablet",
        "serving_size": "1 Tablette",
        "servings_per_container": 240,
        "price": 16.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://www.amazon.de/dp/B07RQLF2NJ",
        "certifications": ["gmp", "vegan"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Vitamin D3 Depot-Tabletten: nur alle 20 Tage 1 Tablette. 240 Stück – Jahresvorrat.",
        "description_en": "Vitamin D3 depot tablets: only 1 tablet every 20 days. 240 pcs – yearly supply.",
    },
    {
        "name": "Vitamin D3 Bio Tropfen",
        "brand": "Sunday Natural",
        "category": "vitamin",
        "ingredients": ["vitamin_d3", "cholecalciferol", "olive_oil"],
        "dosage": "1 Tropfen täglich",
        "form": "liquid",
        "serving_size": "1 Tropfen",
        "servings_per_container": 1150,
        "price": 19.90,
        "currency": "EUR",
        "shop_name": "Sunday Natural",
        "shop_url": "https://www.sunday.de/vitamin-d3-tropfen-bio.html",
        "certifications": ["organic", "vegan"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "strong",
        "description_de": "Bio Vitamin D3 aus Flechten in nativem Olivenöl. 1000 IE pro Tropfen, vegan.",
        "description_en": "Organic Vitamin D3 from lichen in native olive oil. 1000 IU per drop, vegan.",
    },
    # --- Omega-3 Vergleich (4 Varianten) ---
    {
        "name": "Omega-3 Kapseln 1000mg",
        "brand": "Doppelherz",
        "category": "omega",
        "ingredients": ["omega3", "epa", "dha", "fish_oil"],
        "dosage": "1 Kapsel täglich",
        "form": "capsule",
        "serving_size": "1 Kapsel",
        "servings_per_container": 120,
        "price": 11.99,
        "currency": "EUR",
        "shop_name": "Rossmann",
        "shop_url": "https://www.rossmann.de/de/gesundheit-doppelherz-omega-3/p/4009932131826",
        "certifications": [],
        "allergens": ["fish"],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Günstige Omega-3 Kapseln mit Fischöl. 120 Kapseln zum kleinen Preis.",
        "description_en": "Affordable Omega-3 capsules with fish oil. 120 capsules at a low price.",
    },
    {
        "name": "Omega-3 Premium Fischöl",
        "brand": "ESN",
        "category": "omega",
        "ingredients": ["omega3", "epa", "dha", "fish_oil"],
        "dosage": "2 Kapseln täglich",
        "form": "capsule",
        "serving_size": "2 Kapseln",
        "servings_per_container": 75,
        "price": 19.90,
        "currency": "EUR",
        "shop_name": "Fitmart",
        "shop_url": "https://www.fitmart.de/esn-super-omega-3",
        "certifications": ["ifos", "gmp"],
        "allergens": ["fish"],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Premium-Fischöl mit hohem EPA/DHA-Anteil. IFOS-zertifiziert für höchste Reinheit.",
        "description_en": "Premium fish oil with high EPA/DHA content. IFOS-certified for highest purity.",
    },
    {
        "name": "Omega-3 vegan 800mg DHA",
        "brand": "Watson & Son",
        "category": "omega",
        "ingredients": ["omega3", "dha", "epa", "algae_oil"],
        "dosage": "2 Kapseln täglich",
        "form": "capsule",
        "serving_size": "2 Kapseln",
        "servings_per_container": 30,
        "price": 31.90,
        "currency": "EUR",
        "shop_name": "Shop-Apotheke",
        "shop_url": "https://www.shop-apotheke.com/omega-3-vegan-algenoel-kapseln",
        "certifications": ["vegan_society"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Hochdosiertes veganes Omega-3 mit 800mg DHA pro Tagesdosis. Aus Mikroalgen.",
        "description_en": "High-dose vegan Omega-3 with 800mg DHA per daily dose. From microalgae.",
    },
    # --- Zink Vergleich (3 Varianten) ---
    {
        "name": "Zink 15mg Tabletten",
        "brand": "Taxofit",
        "category": "mineral",
        "ingredients": ["zinc", "zinc_gluconate"],
        "dosage": "1 Tablette täglich",
        "form": "tablet",
        "serving_size": "1 Tablette",
        "servings_per_container": 40,
        "price": 3.95,
        "currency": "EUR",
        "shop_name": "Rossmann",
        "shop_url": "https://www.rossmann.de/de/gesundheit-taxofit-zink-15/p/4008617039006",
        "certifications": [],
        "allergens": [],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Einfache Zink-Tabletten aus der Drogerie. Günstig und bewährt.",
        "description_en": "Simple zinc tablets from drugstore. Affordable and proven.",
    },
    {
        "name": "Zink Lutschtabletten mit Histidin",
        "brand": "Pure Encapsulations",
        "category": "mineral",
        "ingredients": ["zinc", "zinc_picolinate", "histidine"],
        "dosage": "1 Lutschtablette täglich",
        "form": "gummy",
        "serving_size": "1 Tablette",
        "servings_per_container": 60,
        "price": 14.90,
        "currency": "EUR",
        "shop_name": "Shop-Apotheke",
        "shop_url": "https://www.shop-apotheke.com/pure-encapsulations-zink-lutschtabletten",
        "certifications": ["gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Premium Zink-Picolinat mit Histidin für verbesserte Aufnahme. Apothekenqualität.",
        "description_en": "Premium zinc picolinate with histidine for improved absorption. Pharmacy quality.",
    },
    # --- Vitamin B12 Vergleich (3 Varianten) ---
    {
        "name": "Vitamin B12 1000µg Depot",
        "brand": "Nature Love",
        "category": "vitamin",
        "ingredients": ["vitamin_b12", "methylcobalamin", "adenosylcobalamin"],
        "dosage": "1 Tablette täglich",
        "form": "tablet",
        "serving_size": "1 Tablette",
        "servings_per_container": 200,
        "price": 18.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://www.amazon.de/dp/B01MSL3CF5",
        "certifications": ["gmp", "vegan"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "B12 mit beiden aktiven Formen (Methyl + Adenosyl). 200 Tabletten Großpackung.",
        "description_en": "B12 with both active forms (Methyl + Adenosyl). 200 tablets bulk pack.",
    },
    {
        "name": "Vitamin B12 Tropfen",
        "brand": "Sunday Natural",
        "category": "vitamin",
        "ingredients": ["vitamin_b12", "methylcobalamin"],
        "dosage": "5 Tropfen täglich",
        "form": "liquid",
        "serving_size": "5 Tropfen",
        "servings_per_container": 120,
        "price": 14.90,
        "currency": "EUR",
        "shop_name": "Sunday Natural",
        "shop_url": "https://www.sunday.de/vitamin-b12-tropfen-methylcobalamin.html",
        "certifications": ["gmp", "vegan"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Flüssiges B12 in Tropfenform für einfache Dosierung. Reines Methylcobalamin.",
        "description_en": "Liquid B12 in drop form for easy dosing. Pure methylcobalamin.",
    },
    # --- Probiotika Vergleich (3 Varianten) ---
    {
        "name": "Probiotik Kapseln 30 Mrd.",
        "brand": "Natural Elements",
        "category": "probiotic",
        "ingredients": ["probiotics", "lactobacillus", "bifidobacterium"],
        "dosage": "1 Kapsel täglich",
        "form": "capsule",
        "serving_size": "1 Kapsel",
        "servings_per_container": 60,
        "price": 18.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://www.amazon.de/dp/B082WNB6V1",
        "certifications": ["gmp", "vegan"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "moderate",
        "description_de": "Probiotika-Komplex mit 21 Bakterienstämmen, 30 Milliarden KBE. Magensaftresistente Kapseln.",
        "description_en": "Probiotic complex with 21 bacterial strains, 30 billion CFU. Acid-resistant capsules.",
    },
    {
        "name": "Probiotik Pulver für Smoothies",
        "brand": "Nupure",
        "category": "probiotic",
        "ingredients": ["probiotics", "lactobacillus", "bifidobacterium", "inulin"],
        "dosage": "1 Messlöffel täglich",
        "form": "powder",
        "serving_size": "2g",
        "servings_per_container": 30,
        "price": 24.90,
        "currency": "EUR",
        "shop_name": "Shop-Apotheke",
        "shop_url": "https://www.shop-apotheke.com/nupure-probiotik-pulver",
        "certifications": ["gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "moderate",
        "description_de": "Probiotik-Pulver zum Einrühren in Smoothies oder Joghurt. Mit Präbiotikum Inulin.",
        "description_en": "Probiotic powder for mixing into smoothies or yogurt. With prebiotic inulin.",
    },
    # --- Kreatin Vergleich (3 Varianten) ---
    {
        "name": "Kreatin Monohydrat Pulver",
        "brand": "Bulk",
        "category": "amino_acid",
        "ingredients": ["creatine", "creatine_monohydrate"],
        "dosage": "5g täglich",
        "form": "powder",
        "serving_size": "5g",
        "servings_per_container": 100,
        "price": 16.99,
        "currency": "EUR",
        "shop_name": "Bulk",
        "shop_url": "https://www.bulk.com/de/kreatin-monohydrat-pulver.html",
        "certifications": ["informed_sport"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Pures Kreatin-Monohydrat ohne Zusätze. 500g Beutel – bestes Preis-Leistungs-Verhältnis.",
        "description_en": "Pure creatine monohydrate without additives. 500g bag – best value for money.",
    },
    {
        "name": "Creatin Kapseln 750mg",
        "brand": "Olimp",
        "category": "amino_acid",
        "ingredients": ["creatine", "creatine_monohydrate"],
        "dosage": "4 Kapseln täglich",
        "form": "capsule",
        "serving_size": "4 Kapseln",
        "servings_per_container": 30,
        "price": 12.90,
        "currency": "EUR",
        "shop_name": "Fitmart",
        "shop_url": "https://www.fitmart.de/olimp-creatine-1250-mega-caps",
        "certifications": ["informed_sport"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Kreatin in praktischer Kapselform. Ideal für unterwegs, kein Mischen nötig.",
        "description_en": "Creatine in convenient capsule form. Ideal on the go, no mixing needed.",
    },
    # --- Ashwagandha Vergleich (3 Varianten) ---
    {
        "name": "Ashwagandha Gummies",
        "brand": "Bears with Benefits",
        "category": "herbal",
        "ingredients": ["ashwagandha", "ksm66", "withanolides"],
        "dosage": "2 Gummies täglich",
        "form": "gummy",
        "serving_size": "2 Gummies",
        "servings_per_container": 30,
        "price": 24.90,
        "currency": "EUR",
        "shop_name": "Douglas",
        "shop_url": "https://www.douglas.de/de/p/bears-with-benefits-ashwagandha-gummies/5012345",
        "certifications": ["vegan"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "moderate",
        "description_de": "Ashwagandha als leckere Gummies mit KSM-66. Stressabbau zum Naschen.",
        "description_en": "Ashwagandha as delicious gummies with KSM-66. Stress relief as a snack.",
    },
    {
        "name": "Ashwagandha 500mg",
        "brand": "Sunday Natural",
        "category": "herbal",
        "ingredients": ["ashwagandha", "withanolides", "ksm66"],
        "dosage": "1 Kapsel täglich",
        "form": "capsule",
        "serving_size": "1 Kapsel",
        "servings_per_container": 120,
        "price": 21.90,
        "currency": "EUR",
        "shop_name": "Sunday Natural",
        "shop_url": "https://www.sunday.de/ashwagandha-ksm66-kapseln.html",
        "certifications": ["gmp", "vegan"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "moderate",
        "description_de": "Hochdosiertes Ashwagandha KSM-66 in Kapseln. 120 Stück für 4 Monate.",
        "description_en": "High-dose Ashwagandha KSM-66 in capsules. 120 pieces for 4 months.",
    },
    # --- Vitamin C Vergleich (3 Varianten) ---
    {
        "name": "Vitamin C 500mg gepuffert",
        "brand": "Pure Encapsulations",
        "category": "vitamin",
        "ingredients": ["vitamin_c", "calcium_ascorbate"],
        "dosage": "1 Kapsel täglich",
        "form": "capsule",
        "serving_size": "1 Kapsel",
        "servings_per_container": 90,
        "price": 22.90,
        "currency": "EUR",
        "shop_name": "Shop-Apotheke",
        "shop_url": "https://www.shop-apotheke.com/pure-encapsulations-vitamin-c-500-gepuffert",
        "certifications": ["gmp"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Magenfreundliches, gepuffertes Vitamin C als Calciumascorbat. Apothekenqualität.",
        "description_en": "Stomach-friendly buffered Vitamin C as calcium ascorbate. Pharmacy quality.",
    },
    {
        "name": "Vitamin C Bio Acerola",
        "brand": "Biotiva",
        "category": "vitamin",
        "ingredients": ["vitamin_c", "acerola", "bioflavonoids"],
        "dosage": "1 Kapsel täglich",
        "form": "capsule",
        "serving_size": "1 Kapsel",
        "servings_per_container": 120,
        "price": 14.99,
        "currency": "EUR",
        "shop_name": "Amazon",
        "shop_url": "https://www.amazon.de/dp/B07BKNL3H2",
        "certifications": ["organic", "vegan"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "strong",
        "description_de": "Natürliches Vitamin C aus Bio-Acerola-Kirsche. Keine synthetische Ascorbinsäure.",
        "description_en": "Natural Vitamin C from organic acerola cherry. No synthetic ascorbic acid.",
    },
    {
        "name": "Vitamin C 1000mg Brausetabletten",
        "brand": "Abtei",
        "category": "vitamin",
        "ingredients": ["vitamin_c", "ascorbic_acid"],
        "dosage": "1 Tablette täglich",
        "form": "tablet",
        "serving_size": "1 Brausetablette",
        "servings_per_container": 15,
        "price": 2.99,
        "currency": "EUR",
        "shop_name": "Rossmann",
        "shop_url": "https://www.rossmann.de/de/gesundheit-abtei-vitamin-c-brausetabletten/p/4026600154802",
        "certifications": [],
        "allergens": [],
        "is_vegan": True,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Vitamin C Brausetabletten mit Orangengeschmack. Günstigste Option im Vergleich.",
        "description_en": "Vitamin C effervescent tablets with orange flavor. Most affordable option.",
    },
    # --- Eisen Vergleich (2 Varianten) ---
    {
        "name": "Ferro Sanol 40mg",
        "brand": "UCB Pharma",
        "category": "mineral",
        "ingredients": ["iron", "iron_glycine_sulfate"],
        "dosage": "1 Kapsel täglich",
        "form": "capsule",
        "serving_size": "1 Kapsel",
        "servings_per_container": 50,
        "price": 9.98,
        "currency": "EUR",
        "shop_name": "Shop-Apotheke",
        "shop_url": "https://www.shop-apotheke.com/ferro-sanol-40mg-kapseln",
        "certifications": [],
        "allergens": [],
        "is_vegan": False,
        "is_organic": False,
        "evidence_level": "strong",
        "description_de": "Bewährtes Apotheken-Eisenpräparat. Gut verträglich dank Glycin-Sulfat-Komplex.",
        "description_en": "Proven pharmacy iron supplement. Well tolerated thanks to glycine sulfate complex.",
    },
    {
        "name": "Eisen Bio Kräuterblut",
        "brand": "Salus",
        "category": "mineral",
        "ingredients": ["iron", "vitamin_c", "b_vitamins", "herbal_extracts"],
        "dosage": "20ml zweimal täglich",
        "form": "liquid",
        "serving_size": "20ml",
        "servings_per_container": 25,
        "price": 18.99,
        "currency": "EUR",
        "shop_name": "DM",
        "shop_url": "https://www.dm.de/salus-kraeuterblut-floradix-p4004148019005.html",
        "certifications": ["organic"],
        "allergens": [],
        "is_vegan": True,
        "is_organic": True,
        "evidence_level": "moderate",
        "description_de": "Bio-Kräuterblut-Saft mit natürlichem Eisen und Vitaminen. Ideal für Schwangere und Veganer.",
        "description_en": "Organic herbal blood tonic with natural iron and vitamins. Ideal for pregnant women and vegans.",
    },
]


def seed_database():
    db = SessionLocal()
    try:
        existing_count = db.query(Supplement).count()
        if existing_count > 0:
            print(f"Database already has {existing_count} supplements. Skipping seed.")
            return

        for data in SAMPLE_SUPPLEMENTS:
            supplement = Supplement(**data)
            db.add(supplement)

        db.commit()
        print(f"Seeded {len(SAMPLE_SUPPLEMENTS)} supplements into database.")
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
